name: G-POINTE
favicon: null
layout_spectrum: 0.4008002975024283
typography_spectrum: 0.26006689900532365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9116860092617571
  lightness: 0.7003287761472166
  saturation: 0.9732348506804556
  rhythmicContrast: 0.364141418132931
purpose: []
